import { config, library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

import {
  faArrowLeft,
  faArrowUpRightFromSquare,
  faBars,
  faBookOpen,
  faCaretDown,
  faChevronLeft,
  faChevronRight,
  faCircleInfo,
  faCircleQuestion,
  faCopy,
  faDownload,
  faDroplet,
  faEraser,
  faFloppyDisk,
  faForwardFast,
  faGift,
  faHand,
  faHeart,
  faInfoCircle,
  faJar,
  faList,
  faMap,
  faPaste,
  faPenToSquare,
  faPeopleGroup,
  faPlus,
  faRecycle,
  faRotateLeft,
  faRotateRight,
  faScrewdriverWrench,
  faSeedling,
  faShareFromSquare,
  faShield,
  faSliders,
  faSquarePlus,
  faStar,
  faTable,
  faTableCellsLarge,
  faTools,
  faTrash,
  faTriangleExclamation,
  faTurnDown,
  faWheatAwn,
  faX,
} from '@fortawesome/free-solid-svg-icons'

import { faDiscord, faGithub } from '@fortawesome/free-brands-svg-icons'

library.add(
  faShield,
  faDroplet,
  faForwardFast,
  faStar,
  faWheatAwn,
  faEraser,
  faCopy,
  faPaste,
  faTrash,
  faTriangleExclamation,
  faPlus,
  faInfoCircle,
  faCaretDown,
  faArrowUpRightFromSquare,
  faCircleInfo,
  faCircleQuestion,
  faJar,
  faSeedling,
  faRecycle,
  faHeart,
  faTools,
  faTableCellsLarge,
  faSquarePlus,
  faTurnDown,
  faArrowLeft,
  faBars,
  faGift,
  faMap,
  faGithub,
  faTable,
  faSliders,
  faX,
  faChevronLeft,
  faChevronRight,
  faDiscord,
  faHand,
  faScrewdriverWrench,
  faRotateRight,
  faRotateLeft,
  faPeopleGroup,
  faBookOpen,
  faList,
  faFloppyDisk,
  faDownload,
  faShareFromSquare,
  faPenToSquare,
  faTrash,
)

// This is important, we are going to let Nuxt worry about the CSS
config.autoAddCss = false

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.component('font-awesome-icon', FontAwesomeIcon)
})
